### ISSUE TITLE
Add meaning full comments to Data-Structures-and-Algorithms/dijkstra_sssp_algorithm.cpp

### ISSUE THREAD

**Issue by vivekcrux** [vivekcrux/Data-Structures-and-Algorithms#4]

**Comment by mkm1997** [comment]
#3 close the issue

**Comment by vivekcrux** [comment]
Merged PR. Thanks for your contribution.

**Comment by zaidishahbaz** [comment]
Are you looking for optimization of the codes on the topics given already or  i can add a few more algorithms to the repository .

**Comment by vivekcrux** [comment]
Thanks @zaidishahbaz go ahead.
